# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Transform-Canvas
version:      0.03
version_from: lib/Transform/Canvas.pm
installdirs:  site
requires:
    Carp:                          0
    SVG:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
