--- #YAML:1.0
name:                Transform-Canvas
version:             0.05
abstract:            Perl extension for performing Coordinate transformation 
license:             ~
author:              
    - Ronan Oger <ronan@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Data::Dumper:                  0
    SVG:                           2.33
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
