--- #YAML:1.0
name:               Transform-Canvas
version:            0.13
abstract:           Perl extension for performing Coordinate transformation 
author:
    - Ronan Oger <ronan@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    Data::Dumper:  0
    SVG::Parser:   0.9
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
